name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          repository: Harjun751/ETI-EduFi-Timetable
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd API
          npm install
          npm install eslint
      - name: Format using ESLint
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          github_token: ${{ secrets.CI_PAT }}
          auto_fix: true
          eslint_dir: API/
